const SVG_PATH = '/svg';

export const hand_icon = `${SVG_PATH}/hand_icon.svg`;
export const Lock = `${SVG_PATH}/lock.svg`;
export const WorldCurrency = `${SVG_PATH}/worldCurrency.svg`;
export const AtmCard = `${SVG_PATH}/atmCard.svg`;
export const OpenAccount = `${SVG_PATH}/openAccount.svg`;
export const verifiedUser = `${SVG_PATH}/verifiedUser.svg`;
export const Authenticator = `${SVG_PATH}/authenticator.svg`;
export const pencil = `${SVG_PATH}/pencil.svg`;
export const success = `${SVG_PATH}/success.svg`;
export const successFull = `${SVG_PATH}/successFull.svg`;
export const arrowRight = `${SVG_PATH}/arrowRight.svg`;
export const arrowLeft = `${SVG_PATH}/arrowLeft.svg`;
export const checkSymbol = `${SVG_PATH}/checkSymbol.svg`;
export const downloadIcon = `${SVG_PATH}/downloadIcon.svg`;
export const pendingIcon = `${SVG_PATH}/pendingIcon.svg`; 
export const closeIcon = `${SVG_PATH}/closeIcon.svg`;
export const cardImg1 = `${SVG_PATH}/cardImg1.jpg`;